### PR TITLE
Implement ABBA-based analysis for chop-and-nod observations

### PR DESCRIPTION
**Pull request by hapipapijuris**
Add ABBA method code #220
Should I add a scan time lapse plot like the figure outputted using pswsc function?

### CODE REVIEW

**Comment by hapipapijuris** [comment]
- Clean up ABBA method code
- delete unnecessary comment
- incorporate "abba" into __all__ and Fire() and func `auto`

**Review by astropenguin — CHANGES_REQUESTED** [review]
Thank you for implementing this feature. Your code assumes that the string `abba` exists somewhere in an observation name but this is not correct. I think you should update `pswsc` function instead of making a new one.

**Comment by astropenguin** [comment]
Minor comments:

1. Why is `.data` used for `abba_cycle` but not for `abba_phase`?
    ```python
    abba_cycle = (scan_onoff.data * 2 + is_second_half - 1) // 4
    abba_phase = (scan_onoff * 2 + is_second_half - 1) % 4
    ```
1. The variable name `da_abba_select` does not look reasonable because it does not select the data anymore.
1. Please keep the plot format align with other functions. For example, the figure size of 6 x 4 inches is not common.
    ```python
    fig, ax = plt.subplots(figsize=(6, 4))
    ```

**Comment by hapipapijuris** [comment]
- incorporate ABBA-based analysis code into pswsc func
- change name `da_abba_select` to `spec`
- make ABBA_PHASE in constant
- change scan_onoff to  scan_onoff.data

**Comment by hapipapijuris** [comment]
I will add changing nod pair code in this issue.  So please do not close.

**Review by astropenguin — CHANGES_REQUESTED** [review]
Thank you for the update. Here are minor comments:

1. Please sort constants alphabetically and use a plural form for the ABBA phases.
2. Please add `subtract_per_abba_cycle` above `subtract_per_scan` (i.e. sort alphabetically).
3. Description of `subtract_per_abba_cycle` looks not correct.
4. Please rename `subtract_per_scan` because now it is not used per scan but per ABBA phase.
5. `ABBA_PHASE == set(...)` (L1177) certainly works but it is not a good coding practice: A comparison (value to be compared) should usually put on the right-hand side. In addition, `.values` does not seem necessary in this case.

**Comment by astropenguin** [comment]
Related to 5., it would be great to check a coding style called "early returns" or "guard clauses".

```python
def subtract_per_abba_cycle(dems: xr.DataArray, /) -> xr.DataArray:
    if not set(np.unique(dems.abba_phase)) == ABBA_PHASES:
        return xr.DataArray(np.nan)

    return (
        dems
        .groupby("abba_phase")
        .map(subtract_per_abba_phase)
        .mean("abba_phase")
    )
```

**Comment by hapipapijuris** [comment]
I changed following Taniguchi-san's comment and reformatted the code.

**Comment by hapipapijuris** [comment]
change explanation of `subtract_per_abba_cycle` and data type `scan_onoff.data` -> `scan_onoff`

**Review by ShinjiFujita — COMMENTED** [review]
I did not find any problems.

**Comment by astropenguin** [comment]
@ShinjiFujita san, thank you for your checking. I will merge the PR and make a new public release soon. By the way, my apologies for keeping your PR #219 still open... I will check it soon as well.

**Pull request merged**
